### ISSUE TITLE
README "how to run" instructions buggy

### ISSUE THREAD

**Issue by ethan-zang** [amsuhane/ACL20-Code-switching-patterns#1]
When attempting any of the run commands provided in the README, there is a `No such file or directory error.`

For example, when attempting ` python Humour/ML/grid_search_baseline.py`, the error is `can't open file 'recreate_results.py': [Errno 2] No such file or directory.`

I have only been able to run `grid_search_baseline.py` when in the ML directories directly. Is this okay? Thanks.

**Comment by amsuhane** [comment]
I have updated the instructions for running the training scripts. Thank you for pointing out the error.
