### ISSUE TITLE
No such file error in Sarcasm ML Baseline

### ISSUE THREAD

**Issue by ethan-zang** [amsuhane/ACL20-Code-switching-patterns#2]
When attempting to run `grid_search.py` in `Sarcasm/ML/Baseline,` the following no such file error arises:

`File "classification.py", line 8, in <module>
    from extract_tweets import get_tweet_map, get_id_truth_map
  File "ACL20-Code-switching-patterns/Sarcasm/ML/Baseline/extract_tweets.py", line 4, in <module>
    fp = open("../Dataset/Sarcasm_tweets_with_language.txt", 'r')
IOError: [Errno 2] No such file or directory: '../Dataset/Sarcasm_tweets_with_language.txt'`

How should we resolve this?

**Comment by amsuhane** [comment]
I have corrected the file paths. The script should run now.

**Comment by ethan-zang** [comment]
`Traceback (most recent call last):
  File "classification.py", line 196, in <module>
    train_and_test()
  File "classification.py", line 180, in train_and_test
    with open('feature_map.pkl', 'rb') as f:
IOError: [Errno 2] No such file or directory: 'feature_map.pkl'
` 

This is my new error.

**Comment by amsuhane** [comment]
I have corrected the issue.

**Comment by ethan-zang** [comment]
Thanks!
