### ISSUE TITLE
pickle error in Humor

### ISSUE THREAD

**Issue by ethan-zang** [amsuhane/ACL20-Code-switching-patterns#3]
Hello,

When I try to run `'python grid_search_baseline.py` or `python3 grid_search_baseline.py` I get a pickling error:

`Traceback (most recent call last):
  File "recreate_results.py", line 78, in <module>
    orignal = pickle.load(fp)
  File "/opt/anaconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/opt/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/anaconda2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4`

Could this be due to an inconsistency on the pickling side? Thanks.

**Comment by amsuhane** [comment]
I tested the script with Python 3.7.10, it is running fine. 
I tested it by running it on google colab using
```
!git clone https://github.com/amsuhane/ACL20-Code-switching-patterns
%cd ACL20-Code-switching-patterns/Humour/ML/
!python grid_search_baseline.py
```

**Comment by ethan-zang** [comment]
Thanks!
