### ISSUE TITLE
Question regarding Pearson's coefficient

### ISSUE THREAD

**Issue by ethan-zang** [amsuhane/ACL20-Code-switching-patterns#4]
I'm wondering how the Pearson's coefficient calculations in `corr.py` relate to Table 2 in https://www.aclweb.org/anthology/2020.acl-main.96.pdf. What operations were performed on the coefficients provided in `corr.py` to achieve the results in Table 2? Thanks!

**Comment by vishal1383** [comment]
Hi @ethan-zang ,

The metrics in table 2, P(T|Q) and avg(S|T) are computed exactly as defined in the paper. corr.py is for experimenting on the Pearson correlation(which is different from metrics in Table 2) of each switching vector feature (X[i][j]) with the ground truth label (y[i]), to see which ones are the most informative features. 

To clarify Table 2 footer: "Table 2: Correlation of switching with different classification tasks.", by correlation we do not mean Pearson's correlation, but we capture the correlation using P(T|Q) and avg(S|T). Pearson's, Kendall, Spearman correlation may also be used to quantify the same among the two random variables, but that's not what is being done in Table-2.

Also, Pearson's correlation mentioned in the paper as "The Pearson’s correlation between a text being sarcastic (hateful) and the text having the property Q is negative -0.17 (-0.04)" is different from what corr.py does. corr.py measures the correlation between features of signal vector and ground truth, while the one described in the paper is between ground truth and Q.

@Srijanb97 @amsuhane to clarify if I am missing something.

Request you to let us know if this clarifies.
Would be happy to help!.

Thanks,
Vishal
